### ISSUE TITLE
Support for a Question with no default for a mandatory answer

### ISSUE THREAD

**Issue by sebbonnet** [plannigan/columbo#488]
As of `0.13.0.post1` there doesn't seem to be a way to have a question without any default where the answer is required.

For instance the following interactions will produce a ValidationError when the user enters no value
```
        columbo.Echo("Please answer the following questions!"),
        columbo.BasicQuestion(
            "concourse_team_name",
            "What is your name?",
            default="",
            validator=is_not_empty,
        ),
```

```
Please answer the following questions!
What is your name? []:

Traceback (most recent call last):
  File "app_template.py", line 334, in <module>
    answers = get_user_answers()
  File "app_template.py", line 318, in get_user_answers
    return columbo.get_answers(interactions_for(default_answers, no_user_input=not user_input),
  File "~/.cache/pypoetry/virtualenvs/python-app-template-7ocZrZks-py3.8/lib/python3.8/site-packages/columbo/_interaction.py", line 680, in get_answers
    result[interaction.name] = interaction.ask(result, no_user_input)
  File "~/.cache/pypoetry/virtualenvs/python-app-template-7ocZrZks-py3.8/lib/python3.8/site-packages/columbo/_interaction.py", line 580, in ask
    raise ValueError(
ValueError: Default value '' must satisfy the validator.
```

I realise this is due to a [code change](https://github.com/plannigan/columbo/blob/v0.13.0.post1/columbo/_interaction.py#L579-L582) that was done recently. Perhaps there is a case for adding another type of Question that has no default? What do you think?

**Comment by plannigan** [comment]
You aren't the first person to ask for this. However, this is one of the tough design aspects of the library. If a default was not required, `no_user_input` would not have a value to fall back to. As a result, it would seem that it would need to raise an exception. Currently the library API has the nice feature of only throwing an exception when something is used in a way that is not compatible with the defined contract (like a type error or re-used answer key).

The linked change was made to address #357, which could cause an infinite loop.

I'm open to discussing it more, but would need to see a proposal that provided a holistic approach for the library as a whole and discussed the trade-offs of the change. To this point, users of the library have accepted the limitation.
